### ISSUE TITLE
How to unlock bootloader for honor devices (as they require unlock code)?

### ISSUE THREAD

**Issue by TechMorgan** [BiltuDas1/unlock-Bootloader#1]

**Comment by BiltuDas1** [comment]
Yes Honor Require Unlock code to unlock it's bootloader, but recently Huwai has stop giving bootloader code so you need to manually generate code.

It can be done using brute force techniques,
for doing this you need to download following tools

[Python3](https://www.python.org/downloads/)

[Huawei-honor-unlock-bootloader](https://github.com/SkyEmie/huawei-honor-unlock-bootloader/archive/refs/heads/master.zip)
[HuaweiBootloaderHack](https://github.com/haexhub/huaweiBootloaderHack/archive/refs/heads/master.zip)

--------------------------------------
Make Sure Developer options and USB debugging is turned on

now you need to create a new folder and extract **Huawei-honor-unlock-bootloader**
after extracting the file, extract and merge **HuaweiBootloaderHack**

Now install your Device Driver and then open cmd into current directory by typing **cmd.exe** into the namebox

Now use the python script to retrieve your Unlock Code

```
python3 unlock.py <IMEI>
```

The tool will generate unlock code for your device (It may take up several days, Please be patient)

**Comment by BiltuDas1** [comment]
There's has some other methods that you can use

• Free Method: (Only Kirin Processor)

Tool - PotatoNV
Requirement - Hardware knowledge

• Paid Method:

Method 1: (Up to Android 7)
Tool - DC Unlocker

Method 2: (From Android 8 and above)
Tool - HCU Client
Requirement - Hardware Knowledge (or) DC Phoenix
