### ISSUE TITLE
Unlock Bootloader for Redmi Note 5pro

### ISSUE THREAD

**Issue by nithish-lkn** [BiltuDas1/unlock-Bootloader#2]
I tried unlocking in my pc it shows unsupported ADB. 
Then I tried using Bugjaegar it shows unknown command ADB. 
Really exhausted trying solutions form my friends. Help me in this! 
![Screenshot_2021-06-03-15-37-04-725_eu sisik hackendebug](https://user-images.githubusercontent.com/85285888/120628216-0b575f00-c482-11eb-991b-cd6bd214c53a.jpg)

**Comment by BiltuDas1** [comment]
Readmi has It's own unlock tool, you need to unlock it's bootloader using a unlock tool, this repo will not help you to unlock bootloader as you see into the first line of the repo

![image](https://user-images.githubusercontent.com/65584801/120635068-a6a00280-c489-11eb-9f9c-bb274cdde501.png)

You need to download Official tool for unlocking your bootloader (Now It unlock bootloader without waiting time) 
https://en.miui.com/unlock/download_en.html

**Comment by nithish-lkn** [comment]
Thank you for the support
