### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Nesqu1k2020** [BiltuDas1/unlock-Bootloader#3]
No working with Samsung s22

**Comment by BiltuDas1** [comment]
What's the Android Version?

**Comment by Nesqu1k2020** [comment]
12

**Comment by BiltuDas1** [comment]
have you read the [README.md](https://github.com/BiltuDas1/unlock-Bootloader/blob/main/README.md) properly?

Clearly Mentioned that
> Please Note: The Repo doesn't work on Android 9 or Above.

**Comment by Nesqu1k2020** [comment]
![6741618D-0AA2-4014-8B8A-E9352C3B0CD4](https://github.com/BiltuDas1/unlock-Bootloader/assets/138229127/7c0bb5d0-e812-4b8e-8ea9-a04f3f75711b)

sorry , when read on my small phone I need to slide to read whole thing , didn’t notice it . Thx
